server:
  port: 8080

spring:
  application:
    name: SpringSecurityWithJWT
  profiles: test
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.xyz.test.com

---
spring:
  application:
    name: SpringSecurityWithJWT
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com